-- backend/scripts/seed_officers.sql
-- Run this script in the Supabase SQL Editor to seed development accounts.

-- NOTE: You must FIRST create the auth.users for these emails using the Supabase Dashboard
-- or the Auth API. Then replace the UUIDs below with the actual user IDs generated by Supabase.

-- Define variables for the UUIDs of your newly created users:
-- Replace these with real UUIDs from your auth.users table
WITH dev_users AS (
  SELECT id, email FROM auth.users WHERE email IN (
    'admin@jannetra.gov', 
    'sector1@jannetra.gov', 
    'officer1@jannetra.gov'
  )
)
-- This is just a conceptual script since we don't know the exact UUIDs.
-- Once you have the UUIDs, you can run the following inserts manually:

/*
-- 1. Create a Jurisdiction
INSERT INTO public.jurisdictions (id, district, sector, description)
VALUES 
  ('d0000000-0000-0000-0000-000000000001', 'Prayagraj', 'Sector 1', 'Central Prayagraj'),
  ('d0000000-0000-0000-0000-000000000002', 'Prayagraj', NULL, 'Entire District');

-- 2. Assign Roles
INSERT INTO public.user_roles (user_id, role)
VALUES 
  ('<UUID_FOR_ADMIN>', 'district_admin'),
  ('<UUID_FOR_SECTOR_OFFICER>', 'sector_officer'),
  ('<UUID_FOR_LOW_LEVEL_OFFICER>', 'low_level_officer');

-- 3. Create Officer Profiles
INSERT INTO public.officer_profiles (user_id, full_name, jurisdiction_id, department, badge_number)
VALUES
  ('<UUID_FOR_ADMIN>', 'Admin User', 'd0000000-0000-0000-0000-000000000002', 'All', 'ADM-001'),
  ('<UUID_FOR_SECTOR_OFFICER>', 'Sector Supervisor', 'd0000000-0000-0000-0000-000000000001', 'Municipal', 'SEC-001'),
  ('<UUID_FOR_LOW_LEVEL_OFFICER>', 'Field Officer', 'd0000000-0000-0000-0000-000000000001', 'Municipal', 'FLD-001');

*/
