import io
from datetime import datetime
from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from ..mongodb import (
    articles_collection, gri_scores_collection, alerts_collection,
    detection_results_collection, sentiment_records_collection, news_articles_collection
)

router = APIRouter(prefix="/api", tags=["Reports"])


async def _build_text_report() -> str:
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    # Use news_articles as primary source
    total = await news_articles_collection.count_documents({})
    gri_agg = await news_articles_collection.aggregate([
        {"$group": {"_id": None, "avg": {"$avg": "$risk_score"}, "max": {"$max": "$risk_score"}}}
    ]).to_list(1)
    avg_gri = gri_agg[0]["avg"] if gri_agg else 0
    max_gri = gri_agg[0]["max"] if gri_agg else 0

    fake = await news_articles_collection.count_documents({"fake_news_label": "FAKE"})
    active_alerts = await alerts_collection.count_documents({"is_active": True})
    if active_alerts == 0:
        active_alerts = await news_articles_collection.count_documents({"risk_level": {"$in": ["HIGH", "MODERATE"]}})
    critical_alerts = await alerts_collection.count_documents({"severity": "CRITICAL", "is_active": True})

    anger_agg = await news_articles_collection.aggregate([
        {"$group": {"_id": None, "avg": {"$avg": "$anger_rating"}}}
    ]).to_list(1)
    avg_anger = anger_agg[0]["avg"] if anger_agg else 0

    cats = await news_articles_collection.aggregate([
        {"$group": {"_id": "$category", "count": {"$sum": 1}, "avg_gri": {"$avg": "$risk_score"}}},
        {"$sort": {"avg_gri": -1}},
    ]).to_list(None)

    top_risks = await news_articles_collection.find({}).sort("risk_score", -1).limit(10).to_list(10)

    sep = "=" * 72
    line = "-" * 72

    report = f"""
{sep}
   GOVERNANCE INTELLIGENCE REPORT
   Predictive Risk Assessment & Decision Support
{sep}
   Generated: {now}
   System: Governance Intelligence DSS v3.0 (MongoDB Backend)
{sep}

1. EXECUTIVE SUMMARY
{line}
   Total Signals Processed:    {total}
   Governance Risk Index (Avg): {avg_gri:.1f} / 100
   Highest GRI Score:          {max_gri:.1f}
   Fake News Detected:         {fake} ({round(fake/max(total,1)*100, 1)}%)
   Active Alerts:              {active_alerts} (Critical: {critical_alerts})
   Average Anger Rating:       {avg_anger:.1f} / 10

2. RISK ASSESSMENT BY CATEGORY
{line}
{"   Category":<30} {"Signals":>8} {"Avg GRI":>10} {"Risk Level":>12}
{line}
"""
    for cat in cats:
        agri = cat.get("avg_gri") or 0
        count = cat.get("count") or 0
        level = "HIGH" if agri > 60 else "MODERATE" if agri > 30 else "LOW"
        cat_name = (cat.get("_id") or "General")[:28]
        report += f"   {cat_name:<28} {count:>8} {agri:>10.1f} {level:>12}\n"

    report += f"""
3. TOP 10 PRIORITY RISKS
{line}
"""
    for i, a in enumerate(top_risks, 1):
        report += f"""   #{i}. {a.get('title', '')}
       Category: {a.get('category', '')} | GRI: {round(a.get('risk_score') or 0, 1)} | Label: {a.get('fake_news_label', '')}
"""

    report += f"""
{sep}
   END OF REPORT
   This report was auto-generated by the Governance Intelligence DSS.
{sep}
"""
    return report


@router.get("/report/download")
async def download_report():
    report_text = await _build_text_report()
    buffer = io.BytesIO(report_text.encode("utf-8"))
    buffer.seek(0)
    filename = f"governance_report_{datetime.utcnow().strftime('%Y%m%d_%H%M')}.txt"
    return StreamingResponse(
        buffer,
        media_type="text/plain",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )


@router.get("/report/preview")
async def preview_report():
    total = await news_articles_collection.count_documents({})
    gri_agg = await news_articles_collection.aggregate([
        {"$group": {"_id": None, "avg": {"$avg": "$risk_score"}}}
    ]).to_list(1)
    avg_gri = round(gri_agg[0]["avg"] if gri_agg else 0, 1)
    fake = await news_articles_collection.count_documents({"fake_news_label": "FAKE"})
    active_alerts = await alerts_collection.count_documents({"is_active": True})

    return {
        "summary": {
            "total_signals": total,
            "avg_gri": avg_gri,
            "fake_news": fake,
            "active_alerts": active_alerts,
        },
        "download_url": "/api/report/download",
    }
